version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: neighbor-net-dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/neighbor-net
      - /neighbor-net/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - neighbor-net
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: >
      /bin/sh -c "apt-get update &&
      apt-get install -y wget gnupg &&
      wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - &&
      echo 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse' | tee /etc/apt/sources.list.d/mongodb-org-4.4.list &&
      apt-get update &&
      apt-get install -y mongodb-mongosh &&
      mongod --bind_ip_all"
    networks:
      - neighbor-net
volumes:
  mongo-data:
networks:
  neighbor-net:
    driver: bridge
