version: "3"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "80:80" # Expose NGINX on port 80
    depends_on:
      - authentication-service
      - chat-service
      - inventory-service
      - news-feed-service
      - search-service
      - frontend
    networks:
      - neighbor-network

  authentication-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    networks:
      - neighbor-network

  chat-service:
    build: ./chat-service
    ports:
      - "3001:3001"
    networks:
      - neighbor-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "3002:3002"
    networks:
      - neighbor-network
    environment:
      - MYSQL_URI=mysql+pymysql://root:password@mysql:3306/inventory_db
    depends_on:
      - mysql
  news-feed-service:
    build: ./news-feed-service
    ports:
      - "3003:3003"
    networks:
      - neighbor-network

  search-service:
    build: ./search-service
    ports:
      - "3004:3004"
    networks:
      - neighbor-network

  frontend:
    build: ./frontend
    ports:
      - "3005:3005"
    networks:
      - neighbor-network

networks:
  neighbor-network:
    driver: bridge
